In [4]:
#ndarray 생성 - 리스트 사용
import numpy as np
A = np.array([[1,2,3],[4,5,6]], dtype=np.int32) # 정수형, 32비트 #dtype = 'i4' 4바이트 (32비트)
print("A :\n", A)

A :
 [[1 2 3]
 [4 5 6]]


In [8]:
#ndarray 생성 - arange() 사용
import numpy as np
A = np.arange(3)
print("A :", A)

A : [0 1 2]


In [12]:
#ndarray 생성 - linspace(), logspace() 사용
import numpy as np
E1 = np.linspace(0.0, 10.0, num=5) # 5개 만들기
print("E1 :", E1)
E2 = np.logspace(0.1, 1, num = 10) # 10개 만들기
print("E2 :", E2)

E1 : [ 0.   2.5  5.   7.5 10. ]
E2 : [ 1.25892541  1.58489319  1.99526231  2.51188643  3.16227766  3.98107171
  5.01187234  6.30957344  7.94328235 10.        ]


In [14]:
#numpy 는 속도가 빠르다.

In [16]:
#ndarray에 대한 인덱싱과 슬라이싱
A = np.arange(10)

A[:5] = 10
print(A)

B = A[5:]
print(B)

B[0] = 20 # shallow copy
print(A)

C = A[5:].copy() # deep copy
B[0] = 30
print(B)

print(A)

[10 10 10 10 10  5  6  7  8  9]
[5 6 7 8 9]
[10 10 10 10 10 20  6  7  8  9]
[30  6  7  8  9]
[10 10 10 10 10 30  6  7  8  9]


In [17]:
#ndarray 배열에 대한 연산

In [ ]:
#ndarray에 대한 관계연산과 논리 연산